# Generated by Django 5.1.3 on 2025-02-10 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NeuronClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
                ('split_lr', models.BooleanField(default=None, help_text='Indicates if the neuron class is split into left/right.', null=True, verbose_name='Split Left/Right')),
                ('split_dv', models.BooleanField(default=None, help_text='Indicates if the neuron class is split into dorsal/ventral.', null=True, verbose_name='Split Dorsal/Ventral')),
                ('split_d_lr', models.BooleanField(default=None, help_text='Indicates if the neuron class is split into dorsal left/right.', null=True, verbose_name='Split Dorsal Left/Right')),
                ('split_v_lr', models.BooleanField(default=None, help_text='Indicates if the neuron class is split into ventral left/right.', null=True, verbose_name='Split Ventral Left/Right')),
            ],
        ),
        migrations.CreateModel(
            name='Neuron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
                ('lr', models.CharField(blank=True, choices=[('l', 'left'), ('r', 'right')], max_length=1)),
                ('dv', models.CharField(blank=True, choices=[('d', 'dorsal'), ('v', 'ventral')], max_length=1)),
                ('in_head', models.BooleanField()),
                ('in_tail', models.BooleanField()),
                ('is_embryonic', models.BooleanField()),
                ('neurotransmitter_type', models.CharField(max_length=5)),
                ('cell_type', models.CharField(max_length=5)),
                ('neuron_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neurons', to='connectome.neuronclass')),
            ],
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_id', models.CharField(max_length=25, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('dataset_type', models.CharField(max_length=10)),
                ('animal_time', models.DecimalField(decimal_places=1, max_digits=3)),
                ('animal_visual_time', models.DecimalField(decimal_places=1, max_digits=3)),
                ('description', models.CharField(max_length=100)),
                ('available_neurons', models.ManyToManyField(related_name='datasets', to='connectome.neuron')),
                ('available_classes', models.ManyToManyField(related_name='datasets', to='connectome.neuronclass')),
            ],
        ),
        migrations.CreateModel(
            name='Synapse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synapse_count', models.PositiveSmallIntegerField()),
                ('synapse_type', models.CharField(choices=[('e', 'electrical'), ('c', 'chemical')], db_index=True, max_length=1)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synapses', to='connectome.dataset')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='connectome.neuron')),
                ('pre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pre', to='connectome.neuron')),
            ],
        ),
    ]
