# Generated by Django 5.2.6 on 2025-09-15 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectome', '0002_dataset_dataset_sha256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neuron',
            name='in_head',
        ),
        migrations.RemoveField(
            model_name='neuron',
            name='in_tail',
        ),
        migrations.RemoveField(
            model_name='neuron',
            name='is_embryonic',
        ),
        migrations.RemoveField(
            model_name='neuron',
            name='neurotransmitter_type',
        ),
        migrations.AddField(
            model_name='neuron',
            name='cell_category',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='neuron',
            name='cell_type_decs',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
