# Generated by Django 5.2.6 on 2025-09-15 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connectome', '0003_remove_neuron_in_head_remove_neuron_in_tail_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='neuron',
            old_name='cell_type_decs',
            new_name='cell_type_desc',
        ),
    ]
