# Generated by Django 5.2.8 on 2026-02-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectome', '0004_rename_cell_type_decs_neuron_cell_type_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neuron',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='neuronclass',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
