# Generated by Django 5.1.3 on 2025-01-06 10:59

import activity.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('connectome', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GCaMPPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_id', models.CharField(max_length=100, unique=True)),
                ('title_full', models.CharField(max_length=300)),
                ('title_short', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GCaMPDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_id', models.CharField(max_length=25, unique=True)),
                ('dataset_type', models.JSONField(default=activity.models.empty_json)),
                ('avg_timestep', models.FloatField(default=0.0)),
                ('max_t', models.PositiveSmallIntegerField(default=0)),
                ('timestamp_confocal', models.JSONField(default=activity.models.empty_json)),
                ('ranges', models.JSONField(default=activity.models.empty_json)),
                ('n_neuron', models.PositiveSmallIntegerField(default=0)),
                ('n_labeled', models.PositiveSmallIntegerField(default=0)),
                ('pumping', models.JSONField(default=activity.models.empty_json)),
                ('head_curvature', models.JSONField(default=activity.models.empty_json)),
                ('body_curvature', models.JSONField(default=activity.models.empty_json)),
                ('angular_velocity', models.JSONField(default=activity.models.empty_json)),
                ('velocity', models.JSONField(default=activity.models.empty_json)),
                ('reversal_events', models.JSONField(default=activity.models.empty_json)),
                ('truncated_pumping', models.JSONField(default=activity.models.empty_json)),
                ('truncated_head_curvature', models.JSONField(default=activity.models.empty_json)),
                ('truncated_body_curvature', models.JSONField(default=activity.models.empty_json)),
                ('truncated_angular_velocity', models.JSONField(default=activity.models.empty_json)),
                ('truncated_velocity', models.JSONField(default=activity.models.empty_json)),
                ('neuron_categorization', models.JSONField(default=activity.models.empty_json)),
                ('encoding_change', models.JSONField(default=activity.models.empty_json)),
                ('rel_enc_str_v', models.JSONField(default=activity.models.empty_json)),
                ('rel_enc_str_θh', models.JSONField(default=activity.models.empty_json)),
                ('rel_enc_str_P', models.JSONField(default=activity.models.empty_json)),
                ('forwardness', models.JSONField(default=activity.models.empty_json)),
                ('dorsalness', models.JSONField(default=activity.models.empty_json)),
                ('feedingness', models.JSONField(default=activity.models.empty_json)),
                ('tau_vals', models.JSONField(default=activity.models.empty_json)),
                ('events', models.JSONField(default=activity.models.empty_json)),
                ('neuron_cor', models.JSONField(default=activity.models.empty_json)),
                ('neuron_cor_original', models.JSONField(default=activity.models.empty_json)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to='activity.gcamppaper')),
            ],
            options={
                'verbose_name': 'GCaMP Dataset',
                'verbose_name_plural': 'GCaMP Datasets',
            },
        ),
        migrations.CreateModel(
            name='GCaMPNeuron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neuron_name', models.CharField(blank=True, max_length=10)),
                ('idx_neuron', models.PositiveIntegerField(default=0)),
                ('lr', models.CharField(choices=[('l', 'left'), ('r', 'right'), ('?', 'unknown'), ('x', 'undefined'), ('n', 'not labeled')], max_length=1)),
                ('dv', models.CharField(choices=[('d', 'dorsal'), ('v', 'ventral'), ('?', 'unknown'), ('x', 'undefined'), ('n', 'not labeled')], max_length=1)),
                ('trace', models.JSONField(default=activity.models.empty_json)),
                ('trace_original', models.JSONField(default=activity.models.empty_json)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neurons', to='activity.gcampdataset')),
                ('neuron_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gcamp_neurons', to='connectome.neuronclass')),
            ],
            options={
                'verbose_name': 'GCaMP Neuron',
                'verbose_name_plural': 'GCaMP Neurons',
                'constraints': [models.UniqueConstraint(fields=('dataset', 'idx_neuron'), name='unique idx_neuron for each dataset')],
            },
        ),
    ]
