# Generated by Django 5.1.3 on 2025-01-25 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gcamppaper',
            name='paper_id_short',
        ),
    ]
