# Generated by Django 6.0.2 on 2026-04-13 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_gcampeventstyle'),
    ]

    operations = [
        migrations.AddField(
            model_name='gcamppaper',
            name='repository_url',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
